# Generated by Django 5.2.13 on 2026-05-25 13:27

import django.db.models.deletion
import django.utils.timezone
import routing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("saved", models.BooleanField(default=False)),
                ("start_point", models.JSONField()),
                ("end_point", models.JSONField()),
                ("start_label", models.CharField(blank=True, max_length=160)),
                ("end_label", models.CharField(blank=True, max_length=160)),
                (
                    "preferences",
                    models.JSONField(default=routing.models._default_preferences),
                ),
                ("route", models.JSONField(default=routing.models._default_route)),
                ("distance_m", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
