# Generated by Django 5.2.13 on 2026-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preference_air_quality",
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="user",
            name="preference_greenery",
            field=models.PositiveSmallIntegerField(default=70),
        ),
        migrations.AddField(
            model_name="user",
            name="preference_noise",
            field=models.PositiveSmallIntegerField(default=55),
        ),
    ]
